[package]
name = "rust-openapi-postman"
version = "0.1.0"
authors = ["Kevin Swiber <kswiber@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openapi = { git = "https://github.com/softprops/openapi" }
convert_case = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["raw_value"]}
regex = "1"
lazy_static = "1.4.0"