[package]
name = "postman2openapi"
version = "0.1.0"
authors = ["Kevin Swiber <kswiber@gmail.com>"]
edition = "2018"

[lib]
name = "postman2openapi"
path = "src/lib.rs"

[[bin]]
name = "postman2openapi"
path = "src/main.rs"

[dependencies]
openapi = { git = "https://github.com/softprops/openapi" }
convert_case = "0.4.0"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["raw_value"]}
regex = "1"
lazy_static = "1.4.0"